#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define PLAYER_SHOT 50
#define ENEMY_SHOT 60
#define SKY 0
#define GROUND 1
#define _NO_OLDNAMES
#define PLAYER 3
#define ENEMY 2
#define DISTANCE 20
#define MAX_X 100
#define MAX_Y 80
#define MIN_X 0
#define MIN_Y 0
#define MAX_TERRAIN_HEIGHT_PLAINS_MAP 60
#define MAX_TERRAIN_INITIAL_HEIGHT_MOUNTAINS_MAP 30
#define MAX_DISTANCE_UNTIL_DEFORMATION_START 10
#define MAX_WIDTH_DEFORMATION 31
#define MAX_HEIGHT_DEFORMATION 75
#define HEIGHT_OFFSET 6
#define MAX_NAME_FILE 35
#define MAX_WIND_SPEED 100
#define VECTOR_LENGTH 1000
#define LENGTH 100
#define HEIGHT 80
#define NUMBER_OF_ARMORS 2
#define ARMOR 4
#define SHOT_TIME 60


#endif // DEFINES_H_INCLUDED
